version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: sh -c "composer require firebase/php-jwt && php -S 0.0.0.0:80 -t public"


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "railway"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "eUCpUvcid6EpFMbuAVXH"
